### ISSUE TITLE
Why is host set to statsd.local in the usage example?

### ISSUE THREAD

**Issue by cmatteri** [50onRed/flask-dogstatsd#10]
Hi,

This is a nice extension. Unfortunately it took me a while to get it working because my dogstatsd server was listening on localhost and this line (```app.config['STATSD_HOST'] = 'statsd.local'```) in the example caused my data to be sent into the void. Statsd's protocol lacks acknowledgements, so I didn't get any error messages from the host setting being incorrect, and it took me a while to realize what was wrong.

So, why is there a line in the example usage that seems to prevent the extension from working with a standard Datadog Agent setup? I noticed that line is also in https://github.com/cyberdelia/flask-statsd. Can it be removed or does it still serve a purpose?

Also the Pypy package is out of date.

Thanks for your work on this.

**Comment by volker48** [comment]
I'll fix that example. The project was originally a fork of the cyberdelia codebase so thats where that came from. Thanks for pointing it out.

**Comment by volker48** [comment]
Fixed https://github.com/50onRed/flask-datadog/commit/e882df545cbff3acf517a1f1f39d8a804c849ff6

**Comment by cmatteri** [comment]
If you prefer, that line could be removed entirely, because STATSD_HOST is [defaulted to localhost if it is not set](https://github.com/50onRed/flask-datadog/blob/master/flask_datadog.py#L87).

**Comment by volker48** [comment]
Thanks, I just took it out since the default is localhost.
