### ISSUE TITLE
Request metric batching

### ISSUE THREAD

**Issue by brettlangdon** [50onRed/flask-dogstatsd#5]
The idea is to allow people to batch all metrics during a single request and flush at the end of the request.

Something similar to the following:

``` python
def before_request():
    statsd.open_buffer(statsd.max_buffer_size)

def after_request():
    statsd.close_buffer()
```

Similar to #4 we could add this by default, and add a config flag to disable (or enable), and/or add a `setup_batching(app)` type method.

**Comment by brettlangdon** [comment]
After some careful thought, this might not be the best/easiest thing to do. Since `DogStatsd` supports metric batching, but it is a global instance batching. So, we would likely need a new instance of `DogStatsd` for each request, which is a bit of overkill, IMHO.

**Comment by volker48** [comment]
Yeah I believe the agent does its own batching before shipping off to datadog. This might be premature optimization.

**Comment by brettlangdon** [comment]
Well, `dogforwarder` will aggregate metrics together before shipping off data to the datadog api, I do not believe `dogstatsd` aggregates anything (I could be wrong though). This batching is more of, batch all statsd calls until the end of the request, instead of making 6 calls, you make 1 at the end of each request.

Could probably be an argument in either direction on whether it is necessary or not, but the point is probably moot by the fact that I don't think we can do it easily anyways :)
