### ISSUE TITLE
Add more default metrics

### ISSUE THREAD

**Issue by brettlangdon** [50onRed/flask-dogstatsd#8]
Since we are adding in the middleware for response time, maybe there are some other default metrics we can provide for people?

An initial thought I had was, `flask.response.size` which is a histogram of `response.headers['Content-Type']`, which we could also tag with `response.mimetype` so you can track response body size.

**Comment by volker48** [comment]
It doesn't tag it but the response size was added here https://github.com/50onRed/flask-datadog/commit/5740caa42a4796a68c12c4a8304bb99da5544a21
